apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}-html
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <body>
        <h1>Hello from gitops-lab</h1>
        <p>{{ .Values.message }}</p>
      </body>
    </html>
